### ISSUE TITLE
Translation

### ISSUE THREAD

**Issue by ghost** [cosp-project/packages_apps_COSPSettings#8]
I finished translating JPN in Crowdin. how about merge it?

**Comment by edi194** [comment]
I've merged them today

**Comment by divadsn** [comment]
@mamarama9904 Yay, new markets

**Comment by ghost** [comment]
hello, I notified not correct approved words in COSP_Updater in Cwordin. would you apply them?

**Comment by edi194** [comment]
Will check today translations and import them
